version: '3.8'

services:
  frontend:
    build:
      context: ./dev/app
      dockerfile: Dockerfile
    image: plant-guard-frontend:production
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend-api

  backend-api:
    build:
      context: ./dev/api
      dockerfile: Dockerfile
    image: plant-guard-backend:production
    env_file:
      - .env
    ports:
      - "8000:8000"
  
